- https://automl.github.io/auto-sklearn/master/

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
from sklearn.metrics import (
        make_scorer,
        confusion_matrix, 
        cohen_kappa_score, 
        accuracy_score, 
        precision_score, 
        recall_score, 
        f1_score, 
        roc_auc_score
)
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

In [3]:
def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return tn / (tn+fp)

In [4]:
METRICS = {
        "accuracy": make_scorer(accuracy_score),
        "precision": make_scorer(precision_score),
        "recall": make_scorer(recall_score),
        "f1": make_scorer(f1_score),
        "AUC": make_scorer(roc_auc_score, needs_proba=True),
        "specificity": make_scorer(specificity_score),
        "kappa":make_scorer(cohen_kappa_score)
}

In [9]:
d = pd.read_csv("data/03-sem-town-shortname.csv")
d.head()

,sales_channel_id,route_id,product_id,weight,pieces,target,state_AGUASCALIENTES,state_BAJA CALIFORNIA NORTE,state_BAJA CALIFORNIA SUR,state_CAMPECHE,...,brand_PUL,brand_RIC,brand_SAN,brand_SL,brand_SUA,brand_SUN,brand_THO,brand_TR,brand_TRI,brand_WON
0,0.0,0.203783,0.861310,0,1,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.0,0.114399,0.025384,0,1,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.124059,0.024763,0,1,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.107077,0.113427,2,2,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0.107484,0.022121,2,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
X, y = d.drop("target", axis=1), d["target"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
import autosklearn.classification
cls = autosklearn.classification.AutoSklearnClassifier()
cls.fit(X_train, y_train)
predictions = cls.predict(X_test)
print("Accuracy score:", sklearn.metrics.accuracy_score(y_test, predictions))

In [ ]:
scores = cross_validate(cls, X, y, cv=splitter, scoring=METRICS)
dt_scores = pd.DataFrame(scores)
pd.DataFrame(dt_scores.mean()).T

This will run for one hour and should result in an accuracy above 0.98.

In [ ]:
if __name__ == "__main__":
    X, y = sklearn.datasets.load_digits(return_X_y=True)
    X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)
    automl = autosklearn.classification.AutoSklearnClassifier()
    automl.fit(X_train, y_train)
    y_hat = automl.predict(X_test)
    print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))

In [10]:
d = d.sample(frac=0.01)
#d.groupby('target').size()/d['target'].count()
d

,sales_channel_id,route_id,product_id,weight,pieces,target,state_AGUASCALIENTES,state_BAJA CALIFORNIA NORTE,state_BAJA CALIFORNIA SUR,state_CAMPECHE,...,brand_PUL,brand_RIC,brand_SAN,brand_SL,brand_SUA,brand_SUN,brand_THO,brand_TR,brand_TRI,brand_WON
21021,0.0,0.117145,0.864132,0,1,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
123065,0.0,0.125991,0.024043,1,2,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
355645,0.0,0.122636,0.023802,2,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
68984,0.0,0.113179,0.177767,2,2,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79824,0.0,0.113280,0.968430,0,0,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611383,0.0,0.144702,0.032951,2,2,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
341840,0.0,0.214765,0.625968,0,0,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
608557,0.0,0.123551,0.698116,2,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
626518,0.0,0.219646,0.610854,0,0,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
345381,0.0,0.207342,0.105839,1,1,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
from sklearn.model_selection import RepeatedStratifiedKFold
from tpot import TPOTClassifier

In [ ]:
# define model evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# define search
model = TPOTClassifier(generations=5, population_size=50, cv=cv, scoring='accuracy', verbosity=2, random_state=1, n_jobs=-1)
# perform the search
model.fit(X, y)
# export the best model
model.export('tpot_best_model.py')

Optimization Progress:   0%|          | 0/300 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.6992274702253357

Generation 2 - Current best internal CV score: 0.7007572509706983

Generation 3 - Current best internal CV score: 0.7038535652062866

Generation 4 - Current best internal CV score: 0.7038535652062866